root: true
extends:
  - eslint:recommended
  - plugin:jest/recommended
  - plugin:vue/vue3-recommended
  - '@vue/eslint-config-typescript/recommended'
  - prettier
env:
  browser: true
  jest: true
  'vue/setup-compiler-macros': true
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  jest/valid-title:
    - error
    - ignoreTypeOfDescribeName: true
  no-undef: off
