# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Nodejs.gitlab-ci.yml

# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:lts-alpine

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

stages:
  - test
  - analyse
  - build
  - deploy

test:
  stage: test
  except:
    - tags
  tags:
    - hdce_docker
  script:
    - npm ci
    - npx prettier --check .
    - npm run test:unit:ci

sast:
  stage: analyse
  when: manual
  tags:
    - hdce_docker

include:
  - template: Security/SAST.gitlab-ci.yml

build:
  stage: build
  except:
    - tags
  tags:
    - hdce_docker
  script:
    - apk add git
    - cp .env.testing_raspberry_pi .env
    - npm run build
    - mv dist/spa dist/spa_raspberry_pi
    - cp .env.testing_variscite_mx8m .env
    - npm run build
    - mv dist/spa dist/spa_variscite_mx8m
    - cp .env.testing_variscite_newtcam2 .env
    - npm run build
    - mv dist/spa dist/spa_variscite_newtcam2
    - cp .env.testing_variscite_newtcam3 .env
    - npm run build
    - mv dist/spa dist/spa_variscite_newtcam3
  artifacts:
    paths:
      - dist/

deploy-raspberry-pi:
  stage: deploy
  except:
    - tags
  tags:
    - hdce_docker
  environment:
    name: Raspberry Pi testing
    url: http://$RASPBERRY_PI_HOST
  script:
    ## Install ssh-agent if not already installed, it is required by Docker.
    - 'which ssh-agent || ( apk update && apk add openssh-client )'

    ## Run ssh-agent (inside the build environment).
    - eval $(ssh-agent -s)

    ## Add the SSH key variable to the agent store. We're using tr to fix line
    ## endings which makes ed25519 keys work without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    - echo "$RASPBERRY_PI_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    ## Create the SSH directory and give it the right permissions.
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    ## Use ssh-keyscan to scan the keys of your private server.
    - ssh-keyscan $RASPBERRY_PI_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    # Deploy.
    - ssh $RASPBERRY_PI_USER@$RASPBERRY_PI_HOST "rm --force --recursive /var/www/html/* && exit"
    - apk add rsync
    - rsync --recursive dist/spa_raspberry_pi/ $RASPBERRY_PI_USER@$RASPBERRY_PI_HOST:/var/www/html

deploy-variscite-mx8m:
  stage: deploy
  except:
    - tags
  tags:
    - hdce_docker
  environment:
    name: Variscite MX8M testing
    url: http://$VARISCITE_MX8M_HOST
  script:
    ## Install ssh-agent if not already installed, it is required by Docker.
    - 'which ssh-agent || ( apk update && apk add openssh-client )'

    ## Run ssh-agent (inside the build environment).
    - eval $(ssh-agent -s)

    ## Add the SSH key variable to the agent store. We're using tr to fix line
    ## endings which makes ed25519 keys work without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    - echo "$VARISCITE_MX8M_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    ## Create the SSH directory and give it the right permissions.
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    ## Use ssh-keyscan to scan the keys of your private server.
    - ssh-keyscan $VARISCITE_MX8M_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    # Deploy.
    - ssh $VARISCITE_USER@$VARISCITE_MX8M_HOST "rm --force --recursive /var/www/html/* && exit"
    - apk add rsync
    - rsync --recursive dist/spa_variscite_mx8m/ $VARISCITE_USER@$VARISCITE_MX8M_HOST:/var/www/html

deploy-variscite-newtcam2:
  stage: deploy
  except:
    - tags
  tags:
    - hdce_docker
  environment:
    name: Variscite NEWTCAM 2 testing
    url: http://$VARISCITE_NEWTCAM2_HOST
  script:
    ## Install ssh-agent if not already installed, it is required by Docker.
    - 'which ssh-agent || ( apk update && apk add openssh-client )'

    ## Run ssh-agent (inside the build environment).
    - eval $(ssh-agent -s)

    ## Add the SSH key variable to the agent store. We're using tr to fix line
    ## endings which makes ed25519 keys work without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    - echo "$VARISCITE_NEWTCAM2_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    ## Create the SSH directory and give it the right permissions.
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    ## Use ssh-keyscan to scan the keys of your private server.
    - ssh-keyscan $VARISCITE_NEWTCAM2_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    # Deploy.
    - ssh $VARISCITE_USER@$VARISCITE_NEWTCAM2_HOST "rm --force --recursive /var/www/html/* && exit"
    - apk add rsync
    - rsync --recursive dist/spa_variscite_newtcam2/ $VARISCITE_USER@$VARISCITE_NEWTCAM2_HOST:/var/www/html

deploy-variscite-newtcam3:
  stage: deploy
  except:
    - tags
  tags:
    - hdce_docker
  environment:
    name: Variscite NEWTCAM 3 testing
    url: http://$VARISCITE_NEWTCAM3_HOST
  script:
    ## Install ssh-agent if not already installed, it is required by Docker.
    - 'which ssh-agent || ( apk update && apk add openssh-client )'

    ## Run ssh-agent (inside the build environment).
    - eval $(ssh-agent -s)

    ## Add the SSH key variable to the agent store. We're using tr to fix line
    ## endings which makes ed25519 keys work without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    - echo "$VARISCITE_NEWTCAM3_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    ## Create the SSH directory and give it the right permissions.
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    ## Use ssh-keyscan to scan the keys of your private server.
    - ssh-keyscan $VARISCITE_NEWTCAM3_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    # Deploy.
    - ssh $VARISCITE_USER@$VARISCITE_NEWTCAM3_HOST "rm --force --recursive /var/www/html/* && exit"
    - apk add rsync
    - rsync --recursive dist/spa_variscite_newtcam3/ $VARISCITE_USER@$VARISCITE_NEWTCAM3_HOST:/var/www/html
