allowBuilds:
  '@parcel/watcher': true
  core-js: true
  electron: false
  electron-winstaller: true
  esbuild: true
  lightningcss: true
  rolldown: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - quasar@2.30.1
