export enum Actions {
  DELETE_FILE = 'DELETE_FILE',
  DELETE_FILES = 'DELETE_FILES',
  FETCH_FILES = 'FETCH_FILES',
  FETCH_SETTINGS = 'FETCH_SETTINGS',
  PATCH_SETTINGS = 'PATCH_SETTINGS',
  PUT_SETTINGS = 'PUT_SETTINGS',
}
